"""
Strix Pro - GitHub Integration Service
PR security reviews, auto-fix, webhook handling
"""

import os
import json
import logging
from typing import Optional, List, Dict
from github import Github, GithubException

logger = logging.getLogger(__name__)

class GitHubService:
    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        self.client = Github(self.token) if self.token else None

    def is_connected(self) -> bool:
        return self.client is not None

    def connect(self, token: str):
        self.token = token
        self.client = Github(token)
        # Verify token
        try:
            user = self.client.get_user()
            return {"connected": True, "user": user.login}
        except GithubException as e:
            raise ValueError(f"Invalid GitHub token: {e}")

    def list_repos(self, limit: int = 50) -> List[Dict]:
        if not self.client:
            raise ValueError("GitHub not connected")
        repos = self.client.get_user().get_repos(sort="updated")
        return [
            {
                "id": r.id,
                "name": r.full_name,
                "description": r.description,
                "language": r.language,
                "stars": r.stargazers_count,
                "private": r.private,
                "updated_at": r.updated_at.isoformat() if r.updated_at else None
            }
            for r in repos[:limit]
        ]

    def get_pr(self, repo_name: str, pr_number: int) -> Dict:
        if not self.client:
            raise ValueError("GitHub not connected")
        repo = self.client.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        return {
            "number": pr.number,
            "title": pr.title,
            "state": pr.state,
            "body": pr.body,
            "files": [f.filename for f in pr.get_files()],
            "additions": pr.additions,
            "deletions": pr.deletions,
            "url": pr.html_url
        }

    def get_pr_diff(self, repo_name: str, pr_number: int) -> str:
        if not self.client:
            raise ValueError("GitHub not connected")
        repo = self.client.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        files = pr.get_files()
        diff_content = ""
        for f in files:
            diff_content += f"\n=== {f.filename} ({f.status}) ===\n"
            diff_content += f.patch or "(binary file)"
        return diff_content

    def create_fix_pr(self, repo_name: str, original_pr: int, fixes: List[Dict], ai_summary: str) -> Dict:
        """Create a PR with security fixes"""
        if not self.client:
            raise ValueError("GitHub not connected")
        repo = self.client.get_repo(repo_name)
        original = repo.get_pull(original_pr)

        # Create branch
        base_branch = original.base.ref
        fix_branch = f"security-fixes/pr-{original_pr}"

        try:
            source = repo.get_branch(base_branch)
            repo.create_git_ref(ref=f"refs/heads/{fix_branch}", sha=source.commit.sha)
        except GithubException:
            pass  # Branch may already exist

        # Apply fixes
        for fix in fixes:
            try:
                contents = repo.get_contents(fix["file"], ref=fix_branch)
                repo.update_file(
                    path=fix["file"],
                    message=f"security: {fix['title']}",
                    content=fix["new_content"],
                    sha=contents.sha,
                    branch=fix_branch
                )
            except GithubException:
                repo.create_file(
                    path=fix["file"],
                    message=f"security: {fix['title']}",
                    content=fix["new_content"],
                    branch=fix_branch
                )

        # Create PR
        pr_body = f"""## Security Fixes for PR #{original_pr}

{ai_summary}

### Fixes Applied:
{chr(10).join(f'- {f["title"]}' for f in fixes)}

---
*Auto-generated by Strix Pro*
"""
        new_pr = repo.create_pull(
            title=f"🔒 Security fixes for PR #{original_pr}",
            body=pr_body,
            head=fix_branch,
            base=base_branch
        )

        return {
            "number": new_pr.number,
            "url": new_pr.html_url,
            "title": new_pr.title
        }

    def add_pr_comment(self, repo_name: str, pr_number: int, comment: str):
        if not self.client:
            raise ValueError("GitHub not connected")
        repo = self.client.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        pr.create_issue_comment(comment)

    def scan_pr_for_vulns(self, repo_name: str, pr_number: int, ai_router=None) -> Dict:
        """Scan PR changes for security vulnerabilities"""
        diff = self.get_pr_diff(repo_name, pr_number)
        pr_info = self.get_pr(repo_name, pr_number)

        # Security patterns to check
        findings = []
        security_patterns = [
            {"pattern": "eval(", "severity": "high", "title": "Use of eval() - potential code injection"},
            {"pattern": "exec(", "severity": "high", "title": "Use of exec() - potential code injection"},
            {"pattern": "innerHTML", "severity": "medium", "title": "innerHTML usage - potential XSS"},
            {"pattern": "dangerouslySetInnerHTML", "severity": "medium", "title": "dangerouslySetInnerHTML - potential XSS"},
            {"pattern": "sql", "severity": "medium", "title": "Raw SQL - potential SQL injection"},
            {"pattern": "password", "severity": "high", "title": "Hardcoded password reference"},
            {"pattern": "secret", "severity": "high", "title": "Hardcoded secret reference"},
            {"pattern": "api_key", "severity": "high", "title": "Hardcoded API key reference"},
            {"pattern": "http://", "severity": "low", "title": "Insecure HTTP URL"},
            {"pattern": "disable", "severity": "medium", "title": "Security feature disabled"},
            {"pattern": "verify=False", "severity": "high", "title": "SSL verification disabled"},
            {"pattern": "pickle", "severity": "high", "title": "Pickle deserialization - potential RCE"},
            {"pattern": "subprocess", "severity": "medium", "title": "Subprocess usage - check for injection"},
        ]

        for p in security_patterns:
            if p["pattern"].lower() in diff.lower():
                findings.append({
                    "title": p["title"],
                    "severity": p["severity"],
                    "pattern": p["pattern"],
                    "file": pr_info["files"][0] if pr_info["files"] else "unknown"
                })

        # AI analysis if available
        ai_analysis = ""
        if ai_router and findings:
            try:
                from src.ai.router import AIMessage
                messages = [
                    AIMessage(role="system", content="Analyze this PR diff for security vulnerabilities. Be concise."),
                    AIMessage(role="user", content=diff[:4000])
                ]
                providers = ai_router.get_available_providers()
                if providers:
                    p = list(providers.keys())[0]
                    m = providers[p][0]
                    resp = ai_router.chat(p, m, messages, max_tokens=1000)
                    ai_analysis = resp.content
            except Exception as e:
                ai_analysis = f"AI analysis failed: {e}"

        return {
            "pr": pr_info,
            "findings": findings,
            "total_findings": len(findings),
            "critical": len([f for f in findings if f["severity"] == "critical"]),
            "high": len([f for f in findings if f["severity"] == "high"]),
            "medium": len([f for f in findings if f["severity"] == "medium"]),
            "low": len([f for f in findings if f["severity"] == "low"]),
            "ai_analysis": ai_analysis
        }
